# -*- coding: utf-8 -*-
"""YOLOv8_Potholes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Ok1KxVOz03VD9jxPNfNmzET-Q3aCDh5
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""## Install YOLOv8

YOLOv8 can be installed in two ways - from the source and via pip. This is because it is the first iteration of YOLO to have an official package.
"""

# Pip install (recommended)

!pip install ultralytics

from IPython import display
display.clear_output()
!yolo mode=checks

from ultralytics import YOLO

from IPython.display import display, Image

"""### 🐍 Python SDK"""

model = YOLO(f'{HOME}/yolov8n.pt')

# Commented out IPython magic to ensure Python compatibility.
#  %cd {HOME}

!pip install roboflow --quiet

from roboflow import Roboflow
rf = Roboflow(api_key="")  # I removed my api key due to privacy concerns. But this code is used to load the dataset
project = rf.workspace("mebe").project("mebe")
dataset = project.version(1).download("yolov8")

"""## Custom Training"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=100 imgsz=640 batch=32

!ls {HOME}/runs/detect/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train4/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train4/results.png', width=600)